### ISSUE TITLE
US23 Refactorizacion de Front y persistencia de datos - 4 h

### ISSUE THREAD

**Issue by MiguelUB** [UB-ES-2022-A2/LaVida-wallapopo#102]

**Comment by MiguelUB** [comment]
La refactorización se encarga d mejorar el UI del front con nuevos estilos y técnicas de CSS
La persistencia de datos se encarga de poder mantener la sesión iniciada
Y la librería de iconos nos dara mas flexibilidad y facilidad de al usarlos

**Comment by chyeyexx7** [comment]
Habían varios bugs y no funcionaba el código, pero los he podido solucionar
